displayName=Bank Item Value
author=Zachary Godsell
description=Overlays bank items with their value and colour-coded highlighting
tags=bank,value,price,overlay,ge,alch
version=
plugins=com.zachgodsell.bankitemvalue.BankItemValuePlugin
build=standard
